#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>
#include <algorithm>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <iostream>
#include <map>
#include <random>
#include <sstream>
#include <string>
#include <vector>
using namespace std;

struct User{string u,p,name,role,dept;};
struct Patient{int id;string token,name,phone,gender,dept,doctor,priority,status,reason,account;time_t at;vector<string> notes;};
struct Appt{int id,pid;string doctor,status;time_t at;};
struct Audit{time_t at;string user,role,action,detail;};
vector<User> users={
 {"admin","Admin@123","Administrator","admin",""},{"reception","Reception@123","Reception Desk","receptionist",""},
 {"sitharth","Sith@123","Sitharth","doctor","General Medicine"},{"jenifar","Jeni@456","Jenifar","doctor","Cardiology"},
 {"berline","bella@789","Berline","doctor","Dermatology"},{"puvanesh","Puvan@321","Puvanesh","doctor","Orthopedics"},{"hari","Hari@654","Hari","doctor","Pediatrics"}};
vector<string> doctors={"Sitharth","Jenifar","Berline","Puvanesh","Hari"};
vector<string> depts={"General Medicine","Cardiology","Dermatology","Orthopedics","Pediatrics"};
map<string,bool> avail={{"Sitharth",1},{"Jenifar",1},{"Berline",1},{"Puvanesh",1},{"Hari",1}};
vector<Patient> ps; vector<Appt> aps; vector<Audit> logs; map<string,string> sessions; int pid=1,tid=1,aid=1; bool paused=false;

string esc(string s){string r;for(char c:s){if(c=='&')r+="&amp;";else if(c=='<')r+="&lt;";else if(c=='>')r+="&gt;";else if(c=='\"')r+="&quot;";else r+=c;}return r;}
string dec(string s){string r;for(size_t i=0;i<s.size();++i){if(s[i]=='+')r+=' ';else if(s[i]=='%'&&i+2<s.size()){auto h=[](char c){if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;if(c>='A'&&c<='F')return c-'A'+10;return 0;};r+=char(h(s[i+1])*16+h(s[i+2]));i+=2;}else r+=s[i];}return r;}
map<string,string> form(string s){map<string,string> m;stringstream q(s);string z;while(getline(q,z,'&')){auto p=z.find('=');if(p!=string::npos)m[dec(z.substr(0,p))]=dec(z.substr(p+1));}return m;}
string now(time_t t=time(nullptr)){tm x{};localtime_r(&t,&x);char b[32];strftime(b,sizeof b,"%d-%m-%Y %H:%M",&x);return b;}
void audit(string u,string r,string a,string d){logs.push_back({time(nullptr),u,r,a,d});if(logs.size()>200)logs.erase(logs.begin());}
User* user(map<string,string>&h){auto c=h.find("cookie");if(c==h.end())return nullptr;auto p=c->second.find("sid=");if(p==string::npos)return nullptr;p+=4;auto e=c->second.find(';',p);string s=c->second.substr(p,e==string::npos?string::npos:e-p);auto it=sessions.find(s);if(it==sessions.end())return nullptr;for(auto &u:users)if(u.u==it->second)return &u;return nullptr;}
string resp(string b,int code=200,string extra=""){string st=code==200?"200 OK":code==401?"401 Unauthorized":code==404?"404 Not Found":"400 Bad Request";return "HTTP/1.1 "+st+"\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: "+to_string(b.size())+"\r\nConnection: close\r\n"+extra+"\r\n"+b;}
string red(string p,string cookie=""){return "HTTP/1.1 302 Found\r\nLocation: "+p+"\r\n"+(cookie.empty()?string():"Set-Cookie: sid="+cookie+"; Path=/; HttpOnly; SameSite=Lax\r\n")+"\r\n";}
string head(string title,User* u=nullptr){string x="<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>"+esc(title)+"</title><style>";
x+=R"CSS(:root{--t:#087f8c;--ink:#172b4d;--mut:#718096;--line:#e7edf4;--bg:#f4f7fb}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:13px Arial,sans-serif}.top{height:68px;background:#fff;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;padding:0 25px}.brand{font-size:19px;font-weight:800}.brand b{background:var(--t);color:#fff;padding:9px;border-radius:10px;margin-right:8px}.user{display:flex;align-items:center;gap:9px}.nav{background:#11263f;display:flex;gap:6px;padding:9px 20px;overflow:auto}.nav a{color:#b9c9dc;text-decoration:none;padding:9px 12px;border-radius:8px;white-space:nowrap}.nav a:hover,.nav .on{background:#203c5c;color:#fff}.main{max-width:1450px;margin:auto;padding:24px}.welcome{display:flex;justify-content:space-between;gap:15px;align-items:center;margin-bottom:18px}.welcome h1{margin:0 0 5px;font-size:24px}.mut{color:var(--mut)}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:13px}.grid2{display:grid;grid-template-columns:1.2fr .8fr;gap:15px}.card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:16px;margin-bottom:15px}.stat strong{display:block;font-size:26px;margin-top:7px}.btn{display:inline-block;border:0;background:#eef3f7;color:#38506a;border-radius:9px;padding:9px 12px;text-decoration:none;font-weight:700;font-size:12px;cursor:pointer}.primary{background:var(--t);color:#fff}.danger{color:#b4232c;background:#fff0f0}.pill{display:inline-block;padding:5px 8px;border-radius:20px;background:#eef3f7;font-size:10px;font-weight:700}.Emergency{background:#fee2e2;color:#b4232c}.Urgent{background:#fef3c7;color:#92400e}.Normal,.Completed,.Available{background:#dcfce7;color:#166534}.Waiting{background:#e0f2fe;color:#075985}.In-Consultation{background:#ede9fe;color:#6d28d9}table{border-collapse:collapse;width:100%;font-size:12px}th{text-align:left;background:#f8fafc;color:#77869a}td,th{padding:10px;border-bottom:1px solid #edf1f5}form{display:grid;gap:9px}.formgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:0 14px}.field{display:grid;gap:6px;margin:5px 0 9px}.field label{font-size:11px;font-weight:700;color:#52647b}.field input,.field select,.field textarea{width:100%;border:1px solid #dce4ed;border-radius:9px;padding:10px;background:#fff}.field textarea{min-height:80px}.login{min-height:100vh;display:grid;place-items:center;padding:20px}.loginbox{background:#fff;width:min(100%,430px);padding:34px;border:1px solid var(--line);border-radius:20px;box-shadow:0 14px 40px #18315312}.demo,.notice{background:#f0f9ff;padding:12px;border-radius:9px;margin-top:14px}.error{color:#c2414b}.empty{text-align:center;color:var(--mut);padding:25px}@media(max-width:850px){.grid{grid-template-columns:repeat(2,1fr)}.grid2,.formgrid{grid-template-columns:1fr}.main{padding:15px}.welcome{align-items:flex-start;flex-direction:column}}@media(max-width:550px){.grid{grid-template-columns:1fr 1fr}.top{padding:0 12px}.main{padding:10px}})CSS";
x+="</style></head><body>";if(u)x+="<header class='top'><div class='brand'><b>✚</b>Smart Hospital</div><div class='user'><b>"+esc(u->name)+"</b> ("+esc(u->role)+") <form method='post' action='/logout' style='display:inline'><button class='btn'>Logout</button></form></div></header>";return x;}
string nav(User&u,string active){vector<string> v=u.role=="patient"?vector<string>{"Overview","My Visits","Appointments","Change Password"}:vector<string>{"Overview","Live Queue","Patients","Appointments","Doctors","Change Password"};if(u.role=="admin"||u.role=="receptionist")v.insert(v.end()-1,"Analytics");if(u.role=="admin")v.insert(v.end()-1,"Audit Log");string x="<nav class='nav'>";for(auto&s:v){string p=s=="Overview"?"/":s=="My Visits"||s=="Patients"?"/patients":s=="Live Queue"?"/queue":s=="Appointments"?"/appointments":s=="Doctors"?"/doctors":s=="Analytics"?"/analytics":s=="Audit Log"?"/audit":"/password";x+=string("<a class='")+(s==active?"on":"")+"' href='"+p+"'>"+esc(s)+"</a>";}return x+"</nav>";}
string login(string e=""){return head("Login")+"<main class='login'><section class='loginbox'><div style='font-size:28px'>✚</div><small style='color:#087f8c;font-weight:700'>PATIENT CARE • QUEUE • PRIORITY</small><h1>Smart Hospital</h1><p class='mut'>Patient Queue & Priority Management System</p>"+(e.empty()?"":"<p class='error'>"+esc(e)+"</p>")+R"HTML(<form method='post' action='/login'><div class='field'><label>Username</label><input name='username' required></div><div class='field'><label>Password</label><input name='password' type='password' required></div><button class='btn primary'>Sign in →</button></form><div class='demo'><b>Patient?</b><p>Create your own patient account. Token is generated later by reception.</p><a class='btn' href='/signup'>Create Patient Account</a></div></section></main></body></html>)HTML";}
string signup(string e=""){return head("Patient Account")+"<main class='login'><section class='loginbox'><h1>Create Patient Account</h1><p class='mut'>This creates only a login account; it does not create a hospital visit token.</p>"+(e.empty()?"":"<p class='error'>"+esc(e)+"</p>")+R"HTML(<form method='post' action='/patient-register'><div class='field'><label>Full name</label><input name='name' required></div><div class='field'><label>Phone</label><input name='phone' required></div><div class='field'><label>Username</label><input name='username' minlength='4' required></div><div class='field'><label>Password</label><input name='password' type='password' minlength='8' required></div><button class='btn primary'>Create Account</button><a class='btn' href='/'>Back to Login</a></form></section></main></body></html>)HTML";}
vector<Patient*> visible(User&u){vector<Patient*> r;for(auto&p:ps)if(u.role=="patient"?p.account==u.u:u.role=="doctor"?p.doctor==u.name:true)r.push_back(&p);return r;}
string table(User&u,vector<Patient*> r){if(r.empty())return "<div class='empty'>No visits found.</div>";string x="<div class='card' style='overflow:auto'><table><tr><th>Token</th><th>Patient</th><th>Department</th><th>Doctor</th><th>Priority</th><th>Status</th><th>Registered</th><th>Actions</th></tr>";for(auto*p:r){x+="<tr><td><b>"+esc(p->token)+"</b></td><td>"+esc(p->name)+"</td><td>"+esc(p->dept)+"</td><td>"+esc(p->doctor)+"</td><td><span class='pill "+esc(p->priority)+"'>"+esc(p->priority)+"</span></td><td><span class='pill "+esc(p->status)+"'>"+esc(p->status)+"</span></td><td>"+now(p->at)+"</td><td><a class='btn' href='/patient?id="+to_string(p->id)+"'>Details</a>"+(u.role=="doctor"||u.role=="admin"?" <a class='btn' href='/note?id="+to_string(p->id)+"'>Note</a> <a class='btn' href='/complete?id="+to_string(p->id)+"'>Complete</a>":"")+(u.role=="admin"||u.role=="receptionist"?" <a class='btn' href='/priority?id="+to_string(p->id)+"'>Priority</a>":"")+"</td></tr>";}return x+"</table></div>";}
string dashboard(User&u,string active){auto r=visible(u);int w=0,c=0,d=0;for(auto*p:r){w+=p->status=="Waiting";c+=p->status=="In Consultation";d+=p->status=="Completed";}string x=head(active,&u)+nav(u,active)+"<main class='main'><div class='welcome'><div><h1>"+esc(active)+"</h1><p class='mut'>Smart Hospital Patient Queue & Priority Management</p></div>"+((u.role=="admin"||u.role=="receptionist")?"<a class='btn primary' href='/register'>+ Register Patient</a>":"")+"</div><div class='grid'><div class='card stat'><small>"+(u.role=="patient"?"My Visits":"Patients")+"</small><strong>"+to_string(r.size())+"</strong></div><div class='card stat'><small>Waiting</small><strong>"+to_string(w)+"</strong></div><div class='card stat'><small>In Consultation</small><strong>"+to_string(c)+"</strong></div><div class='card stat'><small>Completed</small><strong>"+to_string(d)+"</strong></div></div>";
if(active=="Overview"||active=="My Visits"||active=="Patients"){x+=(active=="Overview"?"<div class='grid2'><section>":"");x+=table(u,r);if(active=="Overview")x+="</section><section class='card'><h3>Doctor Availability</h3>";if(active=="Overview"){for(auto&z:doctors)x+="<p>Dr. "+esc(z)+" — <span class='pill "+(avail[z]?"Available":"Waiting")+"'>"+(avail[z]?"Available":"Unavailable")+"</span></p>";x+="</section></div>";}}
else if(active=="Live Queue"){vector<Patient*> q;for(auto&p:ps)if(p.status!="Completed")q.push_back(&p);sort(q.begin(),q.end(),[](auto a,auto b){auto rank=[](string s){return s=="Emergency"?0:s=="Urgent"?1:2;};return rank(a->priority)!=rank(b->priority)?rank(a->priority)<rank(b->priority):a->at<b->at;});x+="<div class='notice'>Queue is <b>"+string(paused?"Paused":"Running")+"</b>. Order: Emergency → Urgent → Normal</div>"+(u.role!="receptionist"?"<a class='btn primary' href='/next'>Call Next Patient</a>":"")+table(u,q);}
else if(active=="Doctors"){x+="<div class='card'><h3>Doctors & Departments</h3><table><tr><th>Doctor</th><th>Department</th><th>Availability</th><th>Assigned</th></tr>";for(size_t i=0;i<doctors.size();i++){int n=count_if(ps.begin(),ps.end(),[&](auto&p){return p.doctor==doctors[i];});x+="<tr><td>Dr. "+esc(doctors[i])+"</td><td>"+esc(depts[i])+"</td><td>"+(avail[doctors[i]]?"Available":"Unavailable")+"</td><td>"+to_string(n)+"</td></tr>";}x+="</table></div>";}
else if(active=="Appointments"){x+=string(u.role=="admin"||u.role=="receptionist"?"<p><a class='btn primary' href='/appointment'>+ Book Appointment</a></p>":"")+"<div class='card' style='overflow:auto'><table><tr><th>Date</th><th>Patient</th><th>Doctor</th><th>Status</th><th>Action</th></tr>";for(auto&a:aps){auto it=find_if(ps.begin(),ps.end(),[&](auto&p){return p.id==a.pid;});if(it==ps.end()||(u.role=="patient"&&it->account!=u.u))continue;x+="<tr><td>"+now(a.at)+"</td><td>"+esc(it->name)+"</td><td>"+esc(a.doctor)+"</td><td>"+esc(a.status)+"</td><td>"+(u.role!="patient"&&a.status=="Booked"?"<a class='btn' href='/appt?id="+to_string(a.id)+"&s=Completed'>Complete</a> <a class='btn danger' href='/appt?id="+to_string(a.id)+"&s=Cancelled'>Cancel</a>":"")+"</td></tr>";}x+="</table></div>";}
else if(active=="Analytics"){x+="<div class='card'><h3>Analytics</h3><p>Total visits: "+to_string(ps.size())+"</p><p>Waiting: "+to_string(count_if(ps.begin(),ps.end(),[](auto&p){return p.status=="Waiting";}))+"</p><p>Completed: "+to_string(count_if(ps.begin(),ps.end(),[](auto&p){return p.status=="Completed";}))+"</p><h4>Patients by doctor</h4>";for(auto&z:doctors)x+="<p>Dr. "+esc(z)+": "+to_string(count_if(ps.begin(),ps.end(),[&](auto&p){return p.doctor==z;}))+"</p>";x+="</div>";}
else if(active=="Audit Log"){x+="<div class='card' style='overflow:auto'><table><tr><th>Time</th><th>User</th><th>Role</th><th>Action</th><th>Details</th></tr>";for(auto&a:logs)x+="<tr><td>"+now(a.at)+"</td><td>"+esc(a.user)+"</td><td>"+esc(a.role)+"</td><td>"+esc(a.action)+"</td><td>"+esc(a.detail)+"</td></tr>";x+="</table></div>";}
else if(active=="Change Password")x+="<div class='card'><h3>Change Password</h3><form method='post' action='/password'><div class='field'><label>Current password</label><input name='old' type='password' required></div><div class='field'><label>New password</label><input name='new' type='password' minlength='8' required></div><button class='btn primary'>Update Password</button></form></div>";
return x+"</main></body></html>";}
string regpage(User&u,string err=""){string x=head("Register Patient",&u)+nav(u,"Patients")+"<main class='main'><div class='card'><h2>Register Patient Visit</h2><p class='mut'>Reception creates the token. Link a previously created patient account if available.</p>"+(err.empty()?"":"<p class='error'>"+esc(err)+"</p>")+"<form method='post' action='/register'><div class='formgrid>"; // fixed below
x="";
x=head("Register Patient",&u)+nav(u,"Patients")+"<main class='main'><div class='card'><h2>Register Patient Visit</h2><p class='mut'>Reception creates the token. Link a previously created patient account if available.</p>"+(err.empty()?"":"<p class='error'>"+esc(err)+"</p>")+"<form method='post' action='/register'><div class='formgrid'>";
for(auto pair:vector<pair<string,string>>{{"name","Patient name"},{"age","Age"},{"phone","Phone"}})x+="<div class='field'><label>"+pair.second+"</label><input name='"+pair.first+"' "+(pair.first=="age"?"type='number'":"")+" required></div>";
x+="<div class='field'><label>Gender</label><select name='gender'><option>Prefer not to say</option><option>Female</option><option>Male</option><option>Other</option></select></div><div class='field'><label>Department</label><select name='dept'>";for(auto&z:depts)x+="<option>"+esc(z)+"</option>";x+="</select></div><div class='field'><label>Doctor</label><select name='doctor'>";for(auto&z:doctors)x+="<option>"+esc(z)+"</option>";x+="</select></div><div class='field'><label>Priority</label><select name='priority'><option>Normal</option><option>Urgent</option><option>Emergency</option></select></div><div class='field'><label>Patient username (optional)</label><input name='account'></div></div><div class='field'><label>Reason</label><textarea name='reason'></textarea></div><button class='btn primary'>Register & Generate Token</button></form></div></main></body></html>";return x;}
Patient* getp(int id){for(auto&p:ps)if(p.id==id)return &p;return nullptr;}
bool can(User&u,Patient&p){return u.role=="admin"||u.role=="receptionist"||(u.role=="doctor"&&u.name==p.doctor)||(u.role=="patient"&&u.u==p.account);}
string handle(string method,string target,string body,map<string,string>&h){auto qp=target.find('?');string path=target.substr(0,qp),qs=qp==string::npos?"":target.substr(qp+1);auto q=form(qs);User* u=user(h);
if(method=="GET"&&path=="/")return u?resp(dashboard(*u,"Overview")):resp(login());
if(method=="GET"&&path=="/signup")return resp(signup());
if(method=="POST"&&path=="/login"){auto f=form(body);for(auto&z:users)if(z.u==f["username"]&&z.p==f["password"]){static mt19937_64 rng(time(nullptr));string sid=to_string(rng())+to_string(rng());sessions[sid]=z.u;audit(z.u,z.role,"LOGIN","Successful login");return red("/",sid);}return resp(login("Invalid username or password"),401);}
if(method=="POST"&&path=="/patient-register"){auto f=form(body);if(f["name"].empty()||f["username"].empty()||f["password"].size()<8)return resp(signup("Please fill all fields. Password must be 8+ characters."),400);for(auto&z:users)if(z.u==f["username"])return resp(signup("Username already exists."),400);users.push_back({f["username"],f["password"],f["name"],"patient",""});audit(f["username"],"patient","SIGNUP","Patient account created");return red("/");}
if(!u)return red("/");
if(method=="POST"&&path=="/logout"){auto c=h.find("cookie");if(c!=h.end()){auto p=c->second.find("sid=");if(p!=string::npos){p+=4;auto e=c->second.find(';',p);sessions.erase(c->second.substr(p,e==string::npos?string::npos:e-p));}}return red("/");}
if(method=="GET"&&path=="/register"){if(u->role!="admin"&&u->role!="receptionist")return resp("Forbidden",401);return resp(regpage(*u));}
if(method=="POST"&&path=="/register"){if(u->role!="admin"&&u->role!="receptionist")return resp("Forbidden",401);auto f=form(body);Patient p{pid++,"T"+to_string(1000+tid++),f["name"],f["phone"],f["gender"],f["dept"],f["doctor"],f["priority"],"Waiting",f["reason"],f["account"],time(nullptr),{}};if(!p.account.empty()){bool ok=false;for(auto&z:users)if(z.u==p.account&&z.role=="patient")ok=true;if(!ok)return resp(regpage(*u,"Patient username not found."),400);}ps.push_back(p);audit(u->u,u->role,"REGISTER_PATIENT","Token "+p.token);return red("/patients");}
if(method=="GET"&&path=="/patient"){auto p=getp(stoi(q["id"]));if(!p||!can(*u,*p))return resp("Forbidden",401);string x=head("Patient Details",u)+nav(*u,u->role=="patient"?"My Visits":"Patients")+"<main class='main'><div class='card'><h2>"+esc(p->name)+"</h2><p><b>"+esc(p->token)+"</b> · "+esc(p->dept)+" · Dr. "+esc(p->doctor)+"</p><p>Status: <span class='pill "+p->status+"'>"+p->status+"</span> Priority: <span class='pill "+p->priority+"'>"+p->priority+"</span></p>"+(u->role!="patient"?"<h3>Consultation Notes</h3>":"");for(auto&n:p->notes)if(u->role!="patient")x+="<div class='notice'>"+esc(n)+"</div>";return resp(x+"<a class='btn' href='/patients'>Back</a></div></main></body></html>");}
if(method=="GET"&&path=="/note"){if(u->role!="doctor"&&u->role!="admin")return resp("Forbidden",401);auto p=getp(stoi(q["id"]));if(!p||!can(*u,*p))return resp("Forbidden",401);return resp(head("Add Note",u)+nav(*u,"Patients")+"<main class='main'><div class='card'><h2>Add Consultation Note</h2><form method='post' action='/note?id="+q["id"]+"'><textarea name='note' required></textarea><button class='btn primary'>Save Note</button></form></div></main></body></html>");}
if(method=="POST"&&path=="/note"){if(u->role!="doctor"&&u->role!="admin")return resp("Forbidden",401);auto p=getp(stoi(q["id"]));if(!p||!can(*u,*p))return resp("Forbidden",401);p->notes.push_back(u->name+" • "+now()+" • "+form(body)["note"]);audit(u->u,u->role,"NOTE","Token "+p->token);return red("/patient?id="+q["id"]);}
if(method=="GET"&&path=="/complete"){if(u->role!="doctor"&&u->role!="admin")return resp("Forbidden",401);auto p=getp(stoi(q["id"]));if(!p||!can(*u,*p))return resp("Forbidden",401);p->status="Completed";audit(u->u,u->role,"COMPLETE","Token "+p->token);return red("/patients");}
if(method=="GET"&&path=="/priority"){if(u->role!="admin"&&u->role!="receptionist")return resp("Forbidden",401);return resp(head("Priority",u)+nav(*u,"Patients")+"<main class='main'><div class='card'><form method='post' action='/priority?id="+q["id"]+"'><select name='priority'><option>Normal</option><option>Urgent</option><option>Emergency</option></select><button class='btn primary'>Update Priority</button></form></div></main></body></html>");}
if(method=="POST"&&path=="/priority"){if(u->role!="admin"&&u->role!="receptionist")return resp("Forbidden",401);auto p=getp(stoi(q["id"]));if(!p)return resp("Not found",404);p->priority=form(body)["priority"];audit(u->u,u->role,"PRIORITY","Token "+p->token);return red("/patients");}
if(method=="GET"&&path=="/next"){if(u->role!="admin"&&u->role!="doctor")return resp("Forbidden",401);if(paused)return resp(head("Queue",u)+nav(*u,"Live Queue")+"<main class='main'><div class='card'><h2>Queue is paused</h2></div></main></body></html>");Patient* best=nullptr;auto rank=[](string s){return s=="Emergency"?0:s=="Urgent"?1:2;};for(auto&p:ps)if(p.status=="Waiting"&&(u->role!="doctor"||p.doctor==u->name))if(!best||rank(p.priority)<rank(best->priority)||(rank(p.priority)==rank(best->priority)&&p.at<best->at))best=&p;if(!best)return resp(head("Queue",u)+nav(*u,"Live Queue")+"<main class='main'><div class='card'><h2>No waiting patients</h2></div></main></body></html>");best->status="In Consultation";audit(u->u,u->role,"CALL_NEXT","Token "+best->token);return red("/queue");}
if(method=="GET"&&path=="/queue")return resp(dashboard(*u,"Live Queue"));
if(method=="GET"&&path=="/patients")return resp(dashboard(*u,u->role=="patient"?"My Visits":"Patients"));
if(method=="GET"&&path=="/doctors")return resp(dashboard(*u,"Doctors"));
if(method=="GET"&&path=="/appointments")return resp(dashboard(*u,"Appointments"));
if(method=="GET"&&path=="/analytics"){if(u->role!="admin"&&u->role!="receptionist")return resp("Forbidden",401);return resp(dashboard(*u,"Analytics"));}
if(method=="GET"&&path=="/audit"){if(u->role!="admin")return resp("Forbidden",401);return resp(dashboard(*u,"Audit Log"));}
if(method=="GET"&&path=="/password")return resp(dashboard(*u,"Change Password"));
if(method=="POST"&&path=="/password"){auto f=form(body);if(f["old"]!=u->p||f["new"].size()<8)return resp(dashboard(*u,"Change Password"),400);u->p=f["new"];audit(u->u,u->role,"PASSWORD_CHANGE","Updated");return red("/");}
if(method=="GET"&&path=="/appointment"){if(u->role!="admin"&&u->role!="receptionist")return resp("Forbidden",401);string x=head("Book Appointment",u)+nav(*u,"Appointments")+"<main class='main'><div class='card'><form method='post' action='/appointment'><select name='pid'>";for(auto&p:ps)x+="<option value='"+to_string(p.id)+"'>"+esc(p.token)+" • "+esc(p.name)+"</option>";x+="</select><select name='doctor'>";for(auto&z:doctors)x+="<option>"+esc(z)+"</option>";return resp(x+"</select><input type='datetime-local' name='at' required><button class='btn primary'>Book Appointment</button></form></div></main></body></html>");}
if(method=="POST"&&path=="/appointment"){if(u->role!="admin"&&u->role!="receptionist")return resp("Forbidden",401);auto f=form(body);aps.push_back({aid++,stoi(f["pid"]),f["doctor"],"Booked",time(nullptr)});audit(u->u,u->role,"APPOINTMENT","Booked");return red("/appointments");}
if(method=="GET"&&path=="/appt"){if(u->role=="patient")return resp("Forbidden",401);for(auto&a:aps)if(a.id==stoi(q["id"]))a.status=q["s"];return red("/appointments");}
return resp("<main class='main'><div class='card'><h2>404</h2><a class='btn' href='/'>Home</a></div></main>",404);
}
void save(){ofstream f("hospital_data.txt");for(auto&p:ps)f<<"P|"<<p.id<<"|"<<p.token<<"|"<<p.name<<"|"<<p.phone<<"|"<<p.gender<<"|"<<p.dept<<"|"<<p.doctor<<"|"<<p.priority<<"|"<<p.status<<"|"<<p.reason<<"|"<<p.account<<"|"<<p.at<<"\n";for(auto&a:aps)f<<"A|"<<a.id<<"|"<<a.pid<<"|"<<a.doctor<<"|"<<a.status<<"|"<<a.at<<"\n";}
void load(){ifstream f("hospital_data.txt");string l;while(getline(f,l)){vector<string>v;stringstream s(l);string z;while(getline(s,z,'|'))v.push_back(z);try{if(v.size()>=13&&v[0]=="P"){Patient p{stoi(v[1]),v[2],v[3],v[4],v[5],v[6],v[7],v[8],v[9],v[10],v[11],stoll(v[12]),{}};ps.push_back(p);pid=max(pid,p.id+1);tid=max(tid,stoi(p.token.substr(1))-999+1);}else if(v.size()>=6&&v[0]=="A"){aps.push_back({stoi(v[1]),stoi(v[2]),v[3],v[4],stoll(v[5])});aid=max(aid,stoi(v[1])+1);}}catch(...){}}}
int main(){load();int port=3000;if(getenv("PORT"))port=atoi(getenv("PORT"));int s=socket(AF_INET,SOCK_STREAM,0);int o=1;setsockopt(s,SOL_SOCKET,SO_REUSEADDR,&o,sizeof o);sockaddr_in a{};a.sin_family=AF_INET;a.sin_addr.s_addr=INADDR_ANY;a.sin_port=htons(port);if(bind(s,(sockaddr*)&a,sizeof a)||listen(s,20)){cerr<<"Server bind/listen failed\n";return 1;}cout<<"Smart Hospital C++ running on port "<<port<<"\n";while(1){int c=accept(s,nullptr,nullptr);if(c<0)continue;string req;char b[8192];int n;while((n=recv(c,b,sizeof b,0))>0){req.append(b,n);if(req.find("\r\n\r\n")!=string::npos)break;}auto e=req.find("\r\n\r\n");string h=req.substr(0,e),body=e==string::npos?"":req.substr(e+4);int need=0;auto cp=h.find("Content-Length:");if(cp!=string::npos)need=stoi(h.substr(cp+15));while((int)body.size()<need){n=recv(c,b,sizeof b,0);if(n<=0)break;body.append(b,n);}stringstream fs(req.substr(0,req.find("\r\n")));string m,t,v;fs>>m>>t>>v;map<string,string> hm;size_t p=req.find("\r\n")+2;while(p<h.size()){size_t z=h.find("\r\n",p);if(z==string::npos||z==p)break;string line=h.substr(p,z-p);auto k=line.find(':');if(k!=string::npos){string key=line.substr(0,k),val=line.substr(k+1);while(!val.empty()&&val[0]==' ')val.erase(0,1);transform(key.begin(),key.end(),key.begin(),::tolower);hm[key]=val;}p=z+2;}string out=handle(m,t,body,hm);send(c,out.data(),out.size(),0);close(c);save();}close(s);}
